version: "3.9"

networks:
  core_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
  net_fiit:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/28
          gateway: 10.0.1.1
  net_fmph:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/28
          gateway: 10.0.2.1
  net_fchpt:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.3.0/28
          gateway: 10.0.3.1

services:
  main-dns:
    image: ubuntu/bind9:latest
    container_name: main-dns
    networks:
      core_net:
        ipv4_address: 10.0.0.7
      net_fiit:
        ipv4_address: 10.0.1.7
      net_fmph:
        ipv4_address: 10.0.2.7
      net_fchpt:
        ipv4_address: 10.0.3.7
    volumes:
      - ./bind/main/named.conf:/etc/bind/named.conf:ro
      - ./bind/main/zones/db.cdn.fiit:/etc/bind/zones/db.cdn.fiit:ro
      - ./bind/main/zones/db.cdn.fmph:/etc/bind/zones/db.cdn.fmph:ro
      - ./bind/main/zones/db.cdn.fchpt:/etc/bind/zones/db.cdn.fchpt:ro
      - ./bind/main/zones/db.cdn.default:/etc/bind/zones/db.cdn.default:ro
    restart: unless-stopped

  secondary-dns:
    image: ubuntu/bind9:latest
    container_name: secondary-dns
    networks:
      core_net:
        ipv4_address: 10.0.0.3
      net_fiit:
        ipv4_address: 10.0.1.5
      net_fmph:
        ipv4_address: 10.0.2.5
      net_fchpt:
        ipv4_address: 10.0.3.5
    volumes:
    - ./bind/named.conf:/etc/bind/named.conf:ro
    - ./bind/zones/db.cdn.fiit:/etc/bind/zones/db.cdn.fiit:ro
    - ./bind/zones/db.cdn.fmph:/etc/bind/zones/db.cdn.fmph:ro
    - ./bind/zones/db.cdn.fchpt:/etc/bind/zones/db.cdn.fchpt:ro
    - ./bind/zones/db.cdn.default:/etc/bind/zones/db.cdn.default:ro  # Add this
    restart: unless-stopped

  origin:
    image: nginx:alpine
    container_name: origin-library
    networks:
      core_net:
        ipv4_address: 10.0.0.8
    volumes:
      - ./origin/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./origin/content:/usr/share/nginx/html:ro
    restart: unless-stopped

  edge-fiit:
    image: nginx:alpine
    container_name: edge-fiit
    networks:
      core_net:
        ipv4_address: 10.0.0.4
      net_fiit:
        ipv4_address: 10.0.1.4
    volumes:
      - ./edge/nginx-fiit.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  edge-fmph:
    image: nginx:alpine
    container_name: edge-fmph
    networks:
      core_net:
        ipv4_address: 10.0.0.5
      net_fmph:
        ipv4_address: 10.0.2.4
    volumes:
      - ./edge/nginx-fmph.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  edge-fchpt:
    image: nginx:alpine
    container_name: edge-fchpt
    networks:
      core_net:
        ipv4_address: 10.0.0.6
      net_fchpt:
        ipv4_address: 10.0.3.4
    volumes:
      - ./edge/nginx-fchpt.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  # Clients point to main-dns IP in their subnet
  client-fiit-1:
    image: curlimages/curl
    container_name: client-fiit-1
    command: ["sleep", "infinity"]
    networks:
      net_fiit: {}
    dns: [10.0.1.7]

  client-fiit-2:
    image: curlimages/curl
    container_name: client-fiit-2
    command: ["sleep", "infinity"]
    networks:
      net_fiit: {}
    dns: [10.0.1.7]

  client-fmph-1:
    image: curlimages/curl
    container_name: client-fmph-1
    command: ["sleep", "infinity"]
    networks:
      net_fmph: {}
    dns: [10.0.2.7]

  client-fmph-2:
    image: curlimages/curl
    container_name: client-fmph-2
    command: ["sleep", "infinity"]
    networks:
      net_fmph: {}
    dns: [10.0.2.7]

  client-fchpt-1:
    image: curlimages/curl
    container_name: client-fchpt-1
    command: ["sleep", "infinity"]
    networks:
      net_fchpt: {}
    dns: [10.0.3.7]

  client-fchpt-2:
    image: curlimages/curl
    container_name: client-fchpt-2
    command: ["sleep", "infinity"]
    networks:
      net_fchpt: {}
    dns: [10.0.3.7]
